"""Constants, paths, dataset registry, and prompt templates for the labeling pipeline."""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
LOGHUB_DIR = DATA_DIR / "loghub"
BATCHES_DIR = DATA_DIR / "batches"
LABELS_DIR = DATA_DIR / "labels"

BATCH_REQUESTS_PATH = BATCHES_DIR / "batch_requests.jsonl"
BATCH_MANIFEST_PATH = BATCHES_DIR / "manifest.json"
BATCH_RESULTS_PATH = BATCHES_DIR / "batch_results.jsonl"

ALL_LABELED_PATH = LABELS_DIR / "all_labeled.jsonl"

MODELS_DIR = DATA_DIR / "models"
MODEL_PATH = MODELS_DIR / "look_skip_model.joblib"
EVAL_REPORT_PATH = MODELS_DIR / "eval_report.json"

# ---------------------------------------------------------------------------
# Dataset registry
# ---------------------------------------------------------------------------
# Each entry: (name, has_ground_truth)
# name is used as the subdirectory on the loghub repo
DATASETS: list[tuple[str, bool]] = [
    ("Android", False),
    ("Apache", False),
    ("BGL", True),
    ("Hadoop", False),
    ("HDFS", False),
    ("HealthApp", False),
    ("HPC", False),
    ("Linux", False),
    ("Mac", False),
    ("OpenSSH", False),
    ("OpenStack", False),
    ("Proxifier", False),
    ("Spark", False),
    ("Thunderbird", True),
    ("Windows", False),
    ("Zookeeper", False),
    # Synthetic error-heavy datasets (generated by generate_error_logs.py)
    ("JavaApp", False),
    ("KernelErrors", False),
    ("DatabaseErrors", False),
    ("WebServer", False),
    ("Microservices", False),
    ("SecurityEvents", False),
]

LOGHUB_BASE_URL = "https://raw.githubusercontent.com/logpai/loghub/master"

# ---------------------------------------------------------------------------
# Labeling parameters
# ---------------------------------------------------------------------------
WINDOW_SIZE = 50  # lines per batch request
MODEL = "claude-haiku-4-5"

# ---------------------------------------------------------------------------
# Prompt templates
# ---------------------------------------------------------------------------
SYSTEM_PROMPT = """\
You are a log-analysis expert. You will be given a window of consecutive log lines \
from a real system. For EACH line, classify it as:

- LOOK: errors, warnings, failures, crashes, anomalies, stack traces, state transitions, \
resource exhaustion, unusual behavior, configuration problems, security events
- SKIP: routine health checks, normal startup/shutdown, periodic INFO heartbeats, \
debug tracing, expected repetitive messages

Lean toward LOOK when in doubt — false positives are cheaper than missed issues.

Return a JSON array with one object per line. Each object has:
  "line": <1-based line number within this window>,
  "label": "LOOK" or "SKIP",
  "reason": <brief reason, max 10 words>

Return ONLY the JSON array, no other text."""

USER_PROMPT_TEMPLATE = """\
System: {dataset}
Lines {start_line}-{end_line} (of {total_lines}):

{lines}"""
